const APP_NAME = 'Hindsight Expert';
const HINDSIGHT_CONTEXT_ID = 'support-agent-v1';
const SUPPORT_SIMILAR_CASE_LIMIT = 5;

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

module.exports = {
  APP_NAME,
  HINDSIGHT_CONTEXT_ID,
  SUPPORT_SIMILAR_CASE_LIMIT,
  HTTP_STATUS
};
