const APP_NAME = 'Hindsight Expert';
const HINDSIGHT_CONTEXT_ID = 'support-agent-v1';
const MAX_SIMILAR_CASES = 5;
const SUPPORT_SIMILAR_CASE_LIMIT = MAX_SIMILAR_CASES;
const GROQ_MODEL = process.env.GROQ_MODEL || 'mixtral-8x7b-32768';
const GROQ_TIMEOUT_MS = 30000;
const MAX_MESSAGE_LENGTH = 5000;
const CONFIDENCE_THRESHOLD = 0.6;

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

module.exports = {
  APP_NAME,
  HINDSIGHT_CONTEXT_ID,
  MAX_SIMILAR_CASES,
  SUPPORT_SIMILAR_CASE_LIMIT,
  GROQ_MODEL,
  GROQ_TIMEOUT_MS,
  MAX_MESSAGE_LENGTH,
  CONFIDENCE_THRESHOLD,
  HTTP_STATUS
};
